### PR TITLE
implement wind

### PR DESCRIPTION
**Pull request by theFox6**
wind changes the direction of rain and snow

### CODE REVIEW

**Comment by Jeija** [comment]
I'm not really maintaining this mod anymore… Would you like to take over? I could transfer this repository over to your account if you are interested.

**Comment by theFox6** [comment]
I could, but I would probably not do much more than you because I currently have much to do with exams that are coming soon.

**Comment by theFox6** [comment]
Nah who cares I still have some time left... if you don't find anyone else and you want to get rid of it I can do it.

**Comment by Jeija** [comment]
Thank you for taking ownership. I squashed all your commits into one and merged them as d434557adfed86b433cd02bb1b42e03ffba72d58. Now I need you to delete your fork of minetest-mod-weather, so that I can transfer you the ownership of the original minetest-mod-weather (otherwise, the two repositories conflict).

**Comment by theFox6** [comment]
done that...

**Comment by Jeija** [comment]
You have to completely delete the minetest-mod-weather repository, not just the branch. The problem is that I can't transfer my repository, because it would get the same URL as your fork at https://github.com/theFox6/minetest-mod-weather

**Pull request closed without merging**
